### ISSUE TITLE
nondeterministic test failures on pypy

### ISSUE THREAD

**Issue by glyph** [twisted/imaginary#64]
This looks like maybe some obscure GC interaction:

```
$ trial -u imaginary.test.test_illumination.DarknessCommandTestCase.test_changeIlluminationLevel
...
Test Pass 18
imaginary.test.test_illumination
  DarknessCommandTestCase
    test_changeIlluminationLevel ...                                     [FAIL]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/Users/glyph/Projects/Imaginary/imaginary/test/test_illumination.py", line 186, in test_changeIlluminationLevel
    [fade_to_black])
  File "/Users/glyph/Projects/Imaginary/imaginary/test/commandutils.py", line 139, in assertCommandOutput
    repr(perspective), s1, s2, i))
twisted.trial.unittest.FailTest: 
'actor' [u'> illuminate 0']
did not match expected
[u'> illuminate 0',
 'Your environs fade to black due to Ineffable Spooky Magic.']
(Line 1)

imaginary.test.test_illumination.DarknessCommandTestCase.test_changeIlluminationLevel
-------------------------------------------------------------------------------
Ran 1 tests in 0.123s

FAILED (failures=1)
```

**Comment by glyph** [comment]
Compounding the impression of a GC interaction, running the tests with `--force-gc` allows me to get to hundreds of successful runs, but every attempt without that flag has failed at <100.  I suspect Axiom's `FinalizingCache`

**Comment by glyph** [comment]
`imaginary.test.test_look.LookTestCase.testLookAroundEventBroadcasting` is a much simpler test method with less going on that fails in a similar way

**Comment by glyph** [comment]
adding some debug prints strongly implies that tests fail when a GC happens (`createCacheRemovalCallback.remove` gets invoked) *during* a call to `runEventTransaction`.

**Comment by glyph** [comment]
OK, so, `Actable.prepare` is getting `None` from `getIntelligence` in the failing case, which should never happen in `imaginary.test.test_look.LookTestCase.testLookAroundEventBroadcasting`.  It makes sense, sort of, that an in-memory ephemeral thing might be GC'd, except for the fact that the `Actor` is a hard reference from the `TestCase`.  Perhaps Axiom `inmemory()` attributes have a bug?

**Comment by glyph** [comment]
Looks like it was just the axiom issue; the builds which were blowing up for me on travis now work thanks to @mithrandi doing a release.
